name: Bug Report
description: Create a report to help us improve the website.
title: "[BUG] "
labels: [type: bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: "## Describe the Bug\nA clear and concise description of what the bug is."

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "To Reproduce"
      description: "Steps to reproduce the behavior:"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."

  - type: dropdown
    id: device
    attributes:
      label: "Device"
      options:
        - Desktop
        - Smartphone
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: "Operating System"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
